#!/bin/sh

# for size in 10000 20000 40000 80000 160000
# do
# 	for order in random sorted reversed
# 	do
# 		echo === Testing Sort A for $order input, size $size ===
# 		for i in 1 2 3 4 5
# 		do
# 			case $order in
# 				random)   flag="R" ;;
# 				sorted)   flag="A" ;;
# 				reversed) flag="D" ;;
# 			esac
# 			{ ./gen $size $flag | /usr/bin/time -f "%U" ./sortA > /dev/null ; }
# 		done
# 		echo ""
# 	done
# done

for size in 10000 20000 40000 80000 160000 32000 64000 128000 256000 512000
do
	for order in random sorted reversed
	do
		echo === Testing Sort B for $order input, size $size ===
		for i in 1 2 3 4 5
		do
			case $order in
				random)   flag="R" ;;
				sorted)   flag="A" ;;
				reversed) flag="D" ;;
			esac
			{ ./gen $size $flag | /usr/bin/time -f "%U" ./sortB > /dev/null ; }
		done
		echo ""
	done
done

